//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFAStudentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processing
    {
        public long ProcID { get; set; }
        public bool InFilingCabinet { get; set; }
        public System.DateTime ProcInQueue { get; set; }
        public Nullable<System.DateTime> ProcToUser { get; set; }
        public Nullable<System.DateTime> ProcUserComplete { get; set; }
        public string Username { get; set; }
        public short QueueID { get; set; }
        public long RecordID { get; set; }
    
        public virtual Queue Queue { get; set; }
        public virtual Record Record { get; set; }
        public virtual User User { get; set; }

        public string status { get; set; }
        
        public void SetStatus()
        {
            if (ProcUserComplete != null)
            {
                status = "Complete";
            } else if (ProcToUser != null)
            {
                status = "Processing";
            } else if (InFilingCabinet == true)
            {
                status = "In Filing Cabinet";
            } else
            {
                status = "In Queue";
            }
        }
    }
}
